name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "ci_test" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Run
        run: make run
